// 更新用户信息
export const ROOT_UPDATE_USER_INFO_MUTATION = 'ROOT_UPDATE_USER_INFO_MUTATION';
export const ROOT_UPDATE_AUTHORIZED_MUTATION = 'ROOT_UPDATE_AUTHORIZED_MUTATION';

// 登录
export const ROOT_LOGIN_URL = '/login';
export const ROOT_LOGIN_ACTION = 'ROOT_LOGIN_ACTION';

// 退出登录
export const ROOT_LOGOUT_URL = '/logout';
export const ROOT_LOGOUT_MUTATION = 'ROOT_LOGOUT_MUTATION';
export const ROOT_LOGOUT_ACTION = 'ROOT_LOGOUT_ACTION';
